### ISSUE TITLE
createContext error with pagination

### ISSUE THREAD

**Issue by zaweb** [react-bootstrap-table/react-bootstrap-table2#648]
Hello. I am trying to add Pagination to my table, but I am getting this error:

> TypeError: props.pagination.createContext is not a function

Here's my render:

```
return (
      <div>
        <ToolkitProvider
          keyField="id"
          data={this.state.data}
          columns={columns}
          search
        >
          {
            props => (
              <div>
                <SearchBar {...props.searchProps}
                  placeholder="Search"
                />
                <hr />
                <BootstrapTable { ...props.baseProps } pagination={ paginationOptions } />
                <br />
              </div>
            )
          }
        </ToolkitProvider>
      </div>
    )
```

It doesn't seem to matter what options I provide, I always get the error. I tried using it outside fo the ToolkitProvider too. Same error. 

I am using react 16.6.0
react-bootstrap-table-next 1.4.0
react-bootstrap-table2-paginator 1.0.3
react-bootstrap-table2-toolkit 1.1.1

Thanks!

**Comment by AllenFang** [comment]
I think you did wrong on `pagination` prop, please check following:

```js
import paginationFactory from 'react-bootstrap-table2-paginator';

<BootstrapTable keyField='id' data={ products } columns={ columns } pagination={ paginationFactory() } />
```

**Comment by belal-mazlom** [comment]
Issue happen with me after upgrade react-bootstrap-table-next from 0.1.15 to 3.0.0
