### ISSUE TITLE
React 19 Incompatibility — findDOMNode crash on Expand Column

### ISSUE THREAD

**Issue by ajayjikadra** [react-bootstrap-table/react-bootstrap-table2#1818]
React 19 Incompatibility — findDOMNode crash on Expand Column

![Image](https://github.com/user-attachments/assets/6e5abb53-ebf7-4d43-85e9-43d597ae4211)

Package:
react-bootstrap-table-next v4.0.3
(and related: react-bootstrap-table2-overlay, react-bootstrap-table2-paginator)

Environment:
React: 19.1.0
Browser: Any (Chrome/Edge/etc.)
Framework: React

❌ Current Behavior
Using the expandRow prop to enable expandable rows causes a runtime crash in React 19.
When using this library with React 19, it throws the following runtime error and breaks the app:

```
Error handled by React Router default ErrorBoundary: 
TypeError: react_dom__WEBPACK_IMPORTED_MODULE_3__.findDOMNode is not a function
    at Transition.performEnter (Transition.js:254:1)
```

Additionally, the console shows:
```
Warning: Transition uses the legacy childContextTypes API which was removed in React 19. 
Use React.createContext() instead. https://react.dev/link/legacy-context
```

This project is still widely used and relied upon for Bootstrap-based data tables. A compatibility update or clear deprecation notice would help the community a lot.

Thank you for maintaining this library!

**Comment by joshlathery** [comment]
Hi, any updates or workarounds for this? Currently trying to get this working in my project use React 19.1.

**Comment by jeff-k-zhou** [comment]
I have forked react-bootstrap-table2 and created [react-bootstrap-table-ng](https://www.npmjs.com/package/react-bootstrap-table-ng). It supports react 18 and 19, also support bootstrap 5.x.
- github repo: https://github.com/jeff-k-zhou/react-bootstrap-table-ng
- docs: https://jeff-k-zhou.github.io/react-bootstrap-table-ng/
- live demo: https://jeff-k-zhou.github.io/react-bootstrap-table-ng/storybook/?path=/docs/welcome--docs

Feel free to give a try and let me know any issues here, https://github.com/jeff-k-zhou/react-bootstrap-table-ng/issues.
