### ISSUE TITLE
TypeError happened on export CSV after js file compression

### ISSUE THREAD

**Issue by xujiahang11** [react-bootstrap-table/react-bootstrap-table2#620]
I was working on a function that export to CSV only selected rows. It went well until I tried to compress my js file. I used several plugins including gulp-minify, gulp-uglify, closure compiler and all got same error: 
```
Uncaught TypeError: c.getSelected is not a function
    at Object.c.handleExportCSV [as onExport] (default.js:956)
    at onClick (default.js:981)
    at Object.y (default.js:70)
    at x (default.js:70)
    at v (default.js:71)
    at t (default.js:72)
    at c (default.js:73)
    at z (default.js:73)
    at d (default.js:72)
    at C (default.js:74)
```

And this is my code:
```
const columns = [{
          dataField: 'id',
          text: 'Category ID'
        }, {
          dataField: 'name',
          text: 'Category Name'
        }];

        const selectRow = {
          mode: 'checkbox',
          clickToSelect: true
        };

        const { ExportCSVButton } = CSVExport;

        return(
            <ToolkitProvider
              keyField="id"
              data={ this.state.categories }
              columns={ columns }
              exportCSV={ {**onlyExportSelection: true**} }>
              {
                props => (
                  <div>
                    <ExportCSVButton { ...props.csvProps }>Export CSV!!</ExportCSVButton>
                    <hr />
                    <BootstrapTable
                      { ...props.baseProps }
                      selectRow={ selectRow }
                    />
                  </div>
                )
              }
            </ToolkitProvider>
        );
```

After it, I also tried setting 'exportAll: false' instead of 'onlyExportSelection: true'. Still got an error:
```
Uncaught TypeError: l.getData is not a function
    at l.handleExportCSV (product.bundle-min.js:1)
    at onClick (product.bundle-min.js:1)
    at Object.<anonymous> (product.bundle-min.js:1)
    at d (product.bundle-min.js:1)
    at product.bundle-min.js:1
    at C (product.bundle-min.js:1)
    at k (product.bundle-min.js:1)
    at j (product.bundle-min.js:1)
    at S (product.bundle-min.js:1)
    at R (product.bundle-min.js:1)
```

I wonder that is there any mistake or potential name conflict error in your source code? Could you check it out? Thank you so much!

**Comment by kmb266** [comment]
I am also getting this issue, but I am using webpack to uglify my code. my error is very similar:
```
Uncaught TypeError: s.getData is not a function
    at s.handleExportCSV (main.js?cdd4c96474ec80a14813:25)
    at onClick (main.js?cdd4c96474ec80a14813:25)
    at Object.<anonymous> (main.js?cdd4c96474ec80a14813:51)
    at Object.invokeGuardedCallback (main.js?cdd4c96474ec80a14813:51)
    at Object.invokeGuardedCallbackAndCatchFirstError (main.js?cdd4c96474ec80a14813:51)
    at R (main.js?cdd4c96474ec80a14813:51)
    at w (main.js?cdd4c96474ec80a14813:51)
    at q (main.js?cdd4c96474ec80a14813:51)
    at P (main.js?cdd4c96474ec80a14813:51)
    at L (main.js?cdd4c96474ec80a14813:51)
```
When I build without minifying, then it succeeds, but shouldn't you want it to work with all minifyers?
I believe that there might be an actual bug. I love the table. 
Thanks for the help!

**Comment by AllenFang** [comment]
I will look into it.

**Comment by kmb266** [comment]
Any update on this issue? Thanks!

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/

Try to upgrade to newest version, I'm not very sure if I fixed it, so please help me to check and tag me if the problem still remain, thanks

**Comment by kmb266** [comment]
@AllenFang I am still getting the error after updating to 1.3.1.
I have found that the error only occurs when I set `exportAll` to false. This might help you in your search to fix the issue. Thanks!

**Comment by xujiahang11** [comment]
+1. Still getting this error. And it also occurs when I set _onlyExportSelection_ to true.

**Comment by andrew-aromin** [comment]
@AllenFang I am running into the exact same issue as @kmb266, using 1.3.1

**Comment by AllenFang** [comment]
thanks you guy, will look into it again 👍

**Comment by kmb266** [comment]
Update here?

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/01/06/version-bump.html)

Please upgrade `react-bootstrap-table-next@2.0.1`, `react-bootstrap-table2-paginator@2.0.1` and `react-bootstrap-table2-toolkit@1.1.2`

**Comment by savan-thakkar** [comment]
@AllenFang 
Getting this error while clicking export csv button.

button.js:33 Uncaught TypeError: onExport is not a function
    at onClick (button.js:33)

Can you please suggest the solution for the same ? Thanks in advance.
