### ISSUE TITLE
Sort and select combination no longer working in 3.3.4

### ISSUE THREAD

**Issue by Mach-5** [react-bootstrap-table/react-bootstrap-table2#1257]
Version 3.3.4 appears to have introduced a bug when using sorting and row selection functionality together. It bug seems to only occur when using custom [Selection Management](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) and having sortable columns.

**Steps to reproduce**

1. Sort by a column
2. Select a row
3. The sorting reverts to the table default

Attempting to sort a column after the issue has occurred also intermittently throws an error (onSort is not a function)

The issue also affects paginated tables using `react-bootstrap-table2-paginator`. When a row is selected it returns to the first page.

**Expected Behaviour**
It is expected that the table will retain the current sorting and pagination state before and after a row is selected. This is the current behaviour for version 3.3.3 and below.

**Code sandbox**
I have created a [sandbox](https://codesandbox.io/s/exciting-fermi-sm44u) that demonstrates the issue. The `react-bootstrap-table-next` package can be toggled to version 3.3.3 to show that the issue was not present before 3.3.4.

**Comment by mathiaswillburger** [comment]
Same here. Since the latest version I am getting immediately the error `Uncaught TypeError: onSort is not a function` after the second sort action. Also the sorting chevrons do not update anymore, which might be related.

Reverting to version react-bootstrap-table-next 3.3.3 solves the issue for now.

**Comment by ricardobarbosahe** [comment]
@mathiaswillburger did you revert the version of any other package like toolkit if you are using it? Reverting the version of react-bootstrap-table-next to 3.3.3 as you said didn't work for me.

**Comment by mathiaswillburger** [comment]
I am currently working with the following set of package versions where it still works for me for now:

```
    "react-bootstrap-table-next": "^3.3.3",
    "react-bootstrap-table2-editor": "^1.4.0",
    "react-bootstrap-table2-filter": "^1.3.0",
    "react-bootstrap-table2-overlay": "^2.0.0",
    "react-bootstrap-table2-paginator": "^2.1.0",
    "react-bootstrap-table2-toolkit": "^2.1.2",
```

**Comment by AllenFang** [comment]
I will take a look on this issue, thanks for bug report

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2020/02/16/version-bump.html

please upgrade to newest version, this bug is a side effect when we handled the sorting issue
